version: '3.1'
services:
    mongo:
        image: mongo
        restart: always
        container_name: scoreboard-db-container
        ports:
            - '30001:27017'
        environment:
            MONGO_INITDB_DATABASE: scoreboard-db
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        volumes:
            - './init-mongo-collection.js:/docker-entrypoint-initdb.d/init-mongo-collection-js:ro'